### ISSUE TITLE
Restrictions 

### ISSUE THREAD

**Issue by VladimirDVV** [OsmSharp/routing#1]
It would be cool to add restrictions on Dykstra algorithm. This is a very useful thing. When will it be added?

**Comment by alecava58** [comment]
It would be useful if you can define some sort of no-go area. It means that you can set one or more areas and assign a penalty if the route cross those areas.
One no-go area would be defined by a location (center) and a radius (meters) and a penalty factor.
This would be useful to avoid that areas if there is an alternative.

**Comment by xivk** [comment]
Everything here is to be replaced by what you can find here:

https://github.com/itinero/routing

Restrictions are supported there.
